---

- name: install the syslinux package
  sudo: true
  pacman: name=syslinux state=present

- name: create the syslinux directory
  sudo: true
  file: path={{ rootfs_mount_point }}/boot/syslinux state=directory

- name: check the status of bootloader
  command: /usr/bin/test -f {{ rootfs_mount_point }}/boot/syslinux/ldlinux.sys
  ignore_errors: true
  changed_when: false
  register: bootloader_installed

- name: install the syslinux bootloader
  sudo: true
  command: /usr/bin/extlinux --install {{ rootfs_mount_point }}/boot/syslinux
  when: bootloader_installed | failed

- name: update the syslinux bootloader
  sudo: true
  command: /usr/bin/extlinux --update {{ rootfs_mount_point }}/boot/syslinux
  when: bootloader_installed | success

# http://www.syslinux.org/wiki/index.php/Mbr
- name: install the master boot record
  sudo: true
  command: /usr/bin/dd bs=440 count=1 conv=notrunc if=/usr/lib/syslinux/bios/gptmbr.bin of={{ rootfs_device }}
  when: bootloader_installed | failed

# http://www.syslinux.org/wiki/index.php/Comboot_API
# http://www.syslinux.org/wiki/index.php/Library_modules
- name: copy the menu.c32 comboot module and its dependencies
  sudo: true
  command: /usr/bin/install -o root -g root -m 0644 /usr/lib/syslinux/bios/{{ item }} {{ rootfs_mount_point }}/boot/syslinux
  with_items:
    - menu.c32
    - libutil.c32

- name: add the syslinux configuration file
  sudo: true
  copy: src=rootfs/boot/syslinux/syslinux.cfg dest={{ rootfs_mount_point }}/boot/syslinux/syslinux.cfg
    owner=root group=root mode=0644
