---
# Install the musl standard C/POSIX library and extensions.

- name: download the musl source code
  get_url: url=http://www.musl-libc.org/releases/musl-{{ musl_version }}.tar.gz
    dest={{ src_dir }}/musl-{{ musl_version }}.tar.gz
  register: downloaded_musl

- name: extract the musl source code
  command: tar -xf musl-{{ musl_version }}.tar.gz
    chdir={{ src_dir }} creates=musl-{{ musl_version }}

- name: configure the musl build options
  command: ./configure --disable-shared
    chdir={{ src_dir }}/musl-{{ musl_version }}
  environment:
    # http://git.musl-libc.org/cgit/musl/tree/configure#n499
    CFLAGS: "-fno-toplevel-reorder"
  when: downloaded_musl.changed

- name: compile the musl library and extensions
  command: make
    chdir={{ src_dir }}/musl-{{ musl_version }}
  when: downloaded_musl.changed

- name: install musl under /usr/local/musl
  sudo: true
  command: make install
    chdir={{ src_dir }}/musl-{{ musl_version }}
  when: downloaded_musl.changed
