---
# Install the musl standard C/POSIX library and extensions.

- name: create the musl build directory
  file: path={{ src_dir }}/musl state=directory
    owner={{ ansible_ssh_user }} group=users mode=0755

- name: copy the musl pkgbuild file
  template: src=musl.PKGBUILD.j2 dest={{ src_dir }}/musl/PKGBUILD
    owner={{ ansible_ssh_user }} group=users mode=0644
  register: musl_pkgbuild

- name: build the musl package
  command: /usr/bin/makepkg --force --syncdeps --clean --noconfirm
    chdir={{ src_dir }}/musl
  when: musl_pkgbuild.changed

- name: install the musl package
  sudo: true
  command: /usr/bin/pacman --upgrade --noconfirm musl-{{ musl_version }}-1-x86_64.pkg.tar.xz
    chdir={{ src_dir }}/musl
  when: musl_pkgbuild.changed
