---
# Compile the BusyBox static binary.

- name: download the latest busybox source
  get_url: url=http://busybox.net/downloads/busybox-{{ busybox_version }}.tar.bz2
    dest={{ src_dir }}/busybox-{{ busybox_version }}.tar.bz2

- name: extract the busybox source
  command: tar -xf busybox-{{ busybox_version }}.tar.bz2
    chdir={{ src_dir }} creates=busybox-{{ busybox_version }}

- name: check for an existing compiled busybox binary
  command: /usr/bin/test -x {{ busybox_binary }}
  ignore_errors: true
  changed_when: false
  register: busybox_compiled

- name: remove the busybox non-source files
  command: /usr/bin/make --silent distclean
    chdir={{ src_dir }}/busybox-{{ busybox_version }}
  when: busybox_compiled | failed

- name: copy the minimal busybox configuration
  copy: src=config dest={{ src_dir }}/busybox-{{ busybox_version }}/.config
  when: busybox_compiled | failed

- name: compile the busybox static binary
  command: /usr/bin/make --jobs={{ nproc.stdout }} --silent
    chdir={{ src_dir }}/busybox-{{ busybox_version }}
  when: busybox_compiled | failed
