---

- name: download the latest busybox source
  get_url: url={{ busybox_mirror }}/{{ busybox_filename }}
    dest={{ src_dir }}/{{ busybox_filename }}

- name: extract the busybox source
  command: tar -xf {{ src_dir }}/{{ busybox_filename }}
    chdir={{ src_dir }} creates={{ busybox_dir }}

- name: check for an existing compiled busybox binary
  command: /usr/bin/test -f {{ busybox_binary }}
  ignore_errors: true
  changed_when: false
  register: busybox_compiled

- name: remove the busybox non-source files
  command: /usr/bin/make --silent distclean
    chdir={{ busybox_dir }}
  when: busybox_compiled | failed

- name: copy the minimal busybox configuration
  copy: src=busybox.config dest={{ busybox_dir }}/.config
  when: busybox_compiled | failed

- name: compile the busybox static binary
  command: /usr/bin/make --jobs={{ nproc.stdout }} --silent
    chdir={{ busybox_dir }}
  when: busybox_compiled | failed
