---
# Generate a cpio archive of the initial RAM file system.

- name: create the initramfs staging directories
  sudo: true
  file: path={{ initramfs_root }}/{{ item }} state=directory
    owner=root group=root mode=0755
  with_items:
    - dev
    - proc
    - sys
    - usr/bin

- name: copy the busybox binary into the initramfs
  sudo: true
  command: /usr/bin/install -D -o root -g root -m 0755 {{ busybox_binary }} {{ initramfs_root }}/usr/bin/busybox

- name: determine which functions are compiled into busybox
  command: "{{ busybox_binary }} --list"
  changed_when: false
  register: busybox_functions

- name: create the busybox function symlinks
  sudo: true
  file: src=busybox dest={{ initramfs_root }}/usr/bin/{{ item }} state=link
    owner=root group=root mode=0755
  with_items: busybox_functions.stdout_lines

- name: copy the init script into the initramfs
  sudo: true
  copy: src=init dest={{ initramfs_root }}/init
    owner=root group=root mode=0755

- name: create the initramfs console device special file
  sudo: true
  command: /usr/bin/mknod {{ initramfs_root }}/dev/console c 5 1
    creates={{ initramfs_root }}/dev/console

- name: create the compressed initramfs archive
  sudo: true
  shell: /usr/bin/find . | /usr/bin/bsdcpio -o -H newc | /usr/bin/xz --check=crc32 --lzma2=dict=512KiB > {{ src_dir }}/initramfs.cpio.xz
    chdir={{ initramfs_root }}
