---
# Compile the execline binaries.

- name: download the latest execline source code
  get_url: url=http://skarnet.org/software/execline/execline-{{ execline_version }}.tar.gz
    dest={{ slashpackage }}/execline-{{ execline_version }}.tar.gz

- name: extract the execline source code
  command: tar -xf execline-{{ execline_version }}.tar.gz
    chdir={{ slashpackage }} creates=admin/execline-{{ execline_version }}

- name: update compilation configs to use musl libc
  copy: src={{ item }} dest={{ slashpackage }}/admin/execline-{{ execline_version }}/conf-compile/{{ item }}
    owner={{ ansible_ssh_user }} group=users mode=0644
  with_items:
    - conf-cc
    - conf-dynld
    - conf-ld

- name: set the search path root to our slashpackage directory
  copy: content={{ slashpackage_prefix }}
    dest={{ slashpackage }}/admin/execline-{{ execline_version }}/conf-compile/conf-sp_root
    owner={{ ansible_ssh_user }} group=users mode=0644

- name: set the allstatic compilation flag
  file: path={{ slashpackage }}/admin/execline-{{ execline_version }}/conf-compile/flag-allstatic state=touch
    owner={{ ansible_ssh_user }} group=users mode=0644

- name: compile the execline binaries
  command: make
    chdir={{ slashpackage }}/admin/execline-{{ execline_version }}

- name: install the execline binaries
  command: make install
    chdir={{ slashpackage }}/admin/execline-{{ execline_version }}
