---
# Compile the s6-linux-utils binaries.

- name: download the latest s6-linux-utils source code
  get_url: url=http://skarnet.org/software/s6-linux-utils/s6-linux-utils-{{ s6_linux_utils_version }}.tar.gz
    dest={{ slashpackage }}/s6-linux-utils-{{ s6_linux_utils_version }}.tar.gz

- name: extract the s6-linux-utils source code
  command: tar -xf s6-linux-utils-{{ s6_linux_utils_version }}.tar.gz
    chdir={{ slashpackage }} creates=admin/s6-linux-utils-{{ s6_linux_utils_version }}

# http://www.openwall.com/lists/musl/2013/10/07/1
#- name: update compilation configs to use musl libc
#  copy: src={{ item }} dest={{ slashpackage }}/admin/s6-linux-utils-{{ s6_linux_utils_version }}/conf-compile/{{ item }}
#    owner={{ ansible_ssh_user }} group=users mode=0644
#  with_items:
#    - conf-cc
#    - conf-dynld
#    - conf-ld
#
- name: link against the static version of libc
  copy: src=conf-ld.gcc dest={{ slashpackage }}/admin/s6-linux-utils-{{ s6_linux_utils_version }}/conf-compile/conf-ld
    owner={{ ansible_ssh_user }} group=users mode=0644

- name: set the search path root to our slashpackage directory
  copy: content={{ slashpackage_prefix }}
    dest={{ slashpackage }}/admin/s6-linux-utils-{{ s6_linux_utils_version }}/conf-compile/conf-sp_root
    owner={{ ansible_ssh_user }} group=users mode=0644

- name: set the allstatic compilation flag
  file: path={{ slashpackage }}/admin/s6-linux-utils-{{ s6_linux_utils_version }}/conf-compile/flag-allstatic state=touch
    owner={{ ansible_ssh_user }} group=users mode=0644

- name: compile the s6-linux-utils binaries
  command: make
    chdir={{ slashpackage }}/admin/s6-linux-utils-{{ s6_linux_utils_version }}

- name: install the s6-linux-utils binaries
  command: make install
    chdir={{ slashpackage }}/admin/s6-linux-utils-{{ s6_linux_utils_version }}
