---
# Compile skalibs, the skarnet.org general-purpose libraries.

- name: download the latest skalibs source code
  get_url: url=http://skarnet.org/software/skalibs/skalibs-{{ skalibs_version }}.tar.gz
    dest={{ slashpackage }}/skalibs-{{ skalibs_version }}.tar.gz

- name: extract the skalibs source code
  command: tar -xf skalibs-{{ skalibs_version }}.tar.gz
    chdir={{ slashpackage }} creates=prog/skalibs-{{ skalibs_version }}

- name: update compilation configs to use musl libc
  copy: src={{ item }} dest={{ slashpackage }}/prog/skalibs-{{ skalibs_version }}/conf-compile/{{ item }}
    owner={{ ansible_ssh_user }} group=users mode=0644
  with_items:
    - conf-cc
    - conf-dynld
    - conf-ld

- name: set the search path root to our slashpackage directory
  copy: content={{ slashpackage_prefix }}
    dest={{ slashpackage }}/prog/skalibs-{{ skalibs_version }}/conf-compile/conf-sp_root
    owner={{ ansible_ssh_user }} group=users mode=0644

- name: set the etc path to our slashpackage directory
  copy: content={{ slashpackage_prefix }}/etc
    dest={{ slashpackage }}/prog/skalibs-{{ skalibs_version }}/conf-compile/conf-etc
    owner={{ ansible_ssh_user }} group=users mode=0644

- name: set the allstatic compilation flag
  file: path={{ slashpackage }}/prog/skalibs-{{ skalibs_version }}/conf-compile/flag-allstatic state=touch
    owner={{ ansible_ssh_user }} group=users mode=0644

- name: compile the skalibs libraries
  command: make
    chdir={{ slashpackage }}/prog/skalibs-{{ skalibs_version }}

- name: install the skalibs libraries
  command: make install
    chdir={{ slashpackage }}/prog/skalibs-{{ skalibs_version }}
